#version 460
#extension GL_EXT_float_e4m3 : require
#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_shuffle : require
#extension GL_GOOGLE_include_directive : require
#define NR_AMD_HARDWARE_NUMERIC 1
#define DLSS_E4M3_HW 1
#include "amd_window_optimized_body.glsl"
