# Compile native AMD/reference shaders without NVIDIA extensions or Python/PTX.
param([ValidateSet('amd','reference','nvidia','all')][string]$Backend = 'amd')
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$glslang = Join-Path $root "tools\glslang\bin\glslang.exe"
$out = Join-Path $root "build\shaders"
New-Item -ItemType Directory -Force $out | Out-Null
$failed = $false
$nativeNames = @('ops','preprocess','window_normalize','global_normalize','portable_gemm','portable_f16','portable_window','portable_global','amd_gemm','amd_window','amd_global','amd_global_matrix','amd_window_normalize','amd_global_normalize')
Get-ChildItem (Join-Path $root "shaders\*.comp") | ForEach-Object {
  if ($Backend -in @('amd','reference') -and $_.BaseName -notin $nativeNames) { return }
  if ($Backend -eq 'nvidia' -and ($_.BaseName.StartsWith('amd_') -or $_.BaseName.StartsWith('portable_'))) { return }
  $target = Join-Path $out ($_.BaseName + ".spv")
  & $glslang -V --target-env vulkan1.3 -I"$root\shaders" $_.FullName -o $target
  if ($LASTEXITCODE -ne 0) { $failed = $true }
}
if ($failed) { exit 1 }
if ($Backend -in @('amd','reference')) { Write-Host "built native $Backend shaders; NVIDIA PTX is disabled"; exit 0 }
# PTX kernels (VK_NV_cuda_kernel_launch): generated by the Python emitters into build/ptx.
$ptxOut = Join-Path $root "build\ptx"
New-Item -ItemType Directory -Force $ptxOut | Out-Null
foreach ($k in 64, 128, 256) {
  python (Join-Path $root "scripts\ptx\mlp_e4m3.py") $k (Join-Path $ptxOut "mlp_e4m3_K$k.ptx") 3 1 1 | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
foreach ($c in 64, 128, 256, 512) {
  python (Join-Path $root "scripts\ptx\qkv_e4m3.py") $c (Join-Path $ptxOut "qkv_e4m3_K$c.ptx") 80 | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
# GEMM + epilogue variants: residual-seeded E4 (5), residual dual (13), plain E4 (4), plain f16 (8), SiLU E4 (6)
foreach ($k in 32, 64, 128, 256, 512, 1024) {
  foreach ($f in 5, 13, 4, 8, 6) {
    python (Join-Path $root "scripts\ptx\gemm2_e4m3.py") $k $f (Join-Path $ptxOut "gemm2_e4m3_K${k}_f$f.ptx") | Out-Null
    if ($LASTEXITCODE -ne 0) { exit 1 }
  }
}
foreach ($cfg in @(@(64, 4, 0), @(128, 4, 0), @(256, 3, 80), @(256, 4, 64))) {
  python (Join-Path $root "scripts\ptx\ffn_e4m3.py") $cfg[0] $cfg[1] (Join-Path $ptxOut "ffn_e4m3_C$($cfg[0])_R$($cfg[1]).ptx") $cfg[2] | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
  python (Join-Path $root "scripts\ptx\ffn_e4m3.py") $cfg[0] $cfg[1] (Join-Path $ptxOut "ffn_e4m3_C$($cfg[0])_R$($cfg[1])_proj.ptx") $cfg[2] 1 | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
foreach ($cfg in @(@(4096, 1, 32, 4), @(1024, 0, 16, 2), @(1024, 1, 8, 4), @(1024, 0, 8, 4))) {
  python (Join-Path $root "scripts\ptx\gemmt_e4m3.py") $cfg[0] $cfg[1] $cfg[2] $cfg[3] (Join-Path $ptxOut "gemmt_e4m3_K$($cfg[0])_f$($cfg[1])_p$($cfg[2])_s$($cfg[3]).ptx") | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
foreach ($cfg in @(@(4, 4), @(2, 8), @(4, 8))) {
  python (Join-Path $root "scripts\ptx\reduce_e4m3.py") $cfg[0] $cfg[1] (Join-Path $ptxOut "reduce_e4m3_s$($cfg[0])_f$($cfg[1]).ptx") | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
foreach ($cfg in @(@(1024, 6, 1), @(4096, 5, 4), @(1024, 8, 2), @(1024, 5, 4))) {
  python (Join-Path $root "scripts\ptx\gemmv_e4m3.py") $cfg[0] $cfg[1] $cfg[2] (Join-Path $ptxOut "gemmv_e4m3_K$($cfg[0])_f$($cfg[1])_s$($cfg[2]).ptx") | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
  # 96-row tiles (two workgroups per SM): 4 A stages x 3 KB + 6 W stages x 4 KB (+ 12 KB residual) = 48 KB
  python (Join-Path $root "scripts\ptx\gemmv_e4m3.py") $cfg[0] $cfg[1] $cfg[2] (Join-Path $ptxOut "gemmv_e4m3_K$($cfg[0])_f$($cfg[1])_s$($cfg[2])_m96.ptx") 4 6 0 0 0 96 | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
foreach ($padded in @(64, 128, 192, 256)) {
  python (Join-Path $root "scripts\ptx\global_attention_e4m3.py") $padded (Join-Path $ptxOut "global_attention_e4m3_p$padded.ptx") | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
# any token count (high resolutions): normalize pass + streamed attention
python (Join-Path $root "scripts\ptx\global_attention_stream_e4m3.py") normalize (Join-Path $ptxOut "global_normalize_e4m3.ptx") | Out-Null
if ($LASTEXITCODE -ne 0) { exit 1 }
python (Join-Path $root "scripts\ptx\global_attention_stream_e4m3.py") attention (Join-Path $ptxOut "global_attention_stream_e4m3.ptx") 4 | Out-Null
if ($LASTEXITCODE -ne 0) { exit 1 }
# split-512 GEMMs through gemmv (96-row tiles, no partition): layer 0 (E4), contract (residual + E4), projection (dual);
# plus the unsplit ViT shapes of high resolutions (many token row groups): contract K4096 f5, qkv K1024 f8, projection K1024 f5
foreach ($cfg in @(@(512, 4), @(512, 5), @(512, 13), @(256, 5), @(4096, 5), @(1024, 8), @(1024, 5))) {
  python (Join-Path $root "scripts\ptx\gemmv_e4m3.py") $cfg[0] $cfg[1] 1 (Join-Path $ptxOut "gemmv_e4m3_K$($cfg[0])_f$($cfg[1])_s1_m96.ptx") 4 6 0 0 0 96 | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
# fused 32-channel block variants: E4 out; E4 + pool; pre + E4 + pool; upres + E4; post + head
foreach ($f in 2, 66, 74, 130, 48) {
  python (Join-Path $root "scripts\ptx\block32_e4m3.py") $f (Join-Path $ptxOut "block32_e4m3_f$f.ptx") | Out-Null
  if ($LASTEXITCODE -ne 0) { exit 1 }
}
